### ISSUE TITLE
Problem with monster stat block

### ISSUE THREAD

**Issue by Nioux** [tcyrus/homebrewery-standalone#3]
When inserting a monster stat block, first part of the table is centered instead of left aligned.

```
___
> ## Mad Koala of the West
>*Tiny fiend, chaotic gossipy*
> ___
> - **Armor Class** 20
> - **Hit Points** 98(1d4 + 5)
> - **Speed** 29ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|16 (+3)|4 (-3)|13 (+2)|2 (-4)|14 (+2)|7 (-1)|
>___
> - **Condition Immunities** buzzed, groggy, drunk
> - **Senses** passive Perception 7
> - **Languages** Latin, Common
> - **Challenge** 4 (7978 XP)
> ___
> ***Pack Tactics.*** These guys work together. Like super well, you don't even know.
>
> ***Fowl Appearance.*** While the creature remains motionless, it is indistinguishable from a normal chicken.
>
> ***Pack Tactics.*** These guys work together. Like super well, you don't even know.
> ### Actions
> ***Tilt-a-whirl Eye Takedown.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
> ***Corkscrew Strike.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 


```

![image](https://user-images.githubusercontent.com/8601237/111349992-f12b9300-8681-11eb-91c5-4c0c7e2a03be.png)

**Comment by tcyrus** [comment]
Sorry for the delay in response. Thanks for bringing this to my attention.

These things should fix the issue (code changes):
- Update markdown parsing code ([link](https://github.com/naturalcrit/homebrewery/blob/master/shared/naturalcrit/markdown.js))
- Update styles ([link](https://github.com/naturalcrit/homebrewery/tree/master/client/homebrew/phbStyle))

I'll take a look at this when I get a chance, but I can't make any guarantees on when that will be.

**Comment by Nioux** [comment]
Thanks for your reply !

I tried to change the markdown.js and phbStyle directory, with no success.

First I had to add "lodash" to dependencies in package.json. 
Then, after replacing the markdown.js, build was still working, but still with the problem with monster tables.
Finally, after replacing phbStyle, everything was broken.

I will try to figure why.

**Comment by tcyrus** [comment]
Sorry if I was unclear. Updating those components isn't as easy as copying the files over.

It looks like they're working on a new version of the renderer and have marked the current renderer as legacy, so some of those links didn't point to the right files.

I'll be pushing out fixes later today.

**Comment by Nioux** [comment]
Last update solved this issue !

Thanks a lot :-)
